name: Django CI

on: [pull_request, push]


jobs:
    unit-testing:
        name: Unit Testing on Github Action
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Run unit tests
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Tests
          run: |
            python manage.py test
